name: Deploy Docs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Створюємо структуру папок для сайту
      - name: Prepare Public Folder
        run: |
          mkdir public
          mkdir -p public/lab3
          mkdir -p public/project

      # Копіюємо ВЖЕ ГОТОВІ html папки
      - name: Copy Files
        run: |
          cp -r Lab_3/html/* public/lab3/
          cp -r Project_2/html/* public/project/

      # Публікуємо
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
