name: Generate Doxygen Docs

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      # Запускаємо перший Doxyfile (вкажіть правильний шлях до нього
      - name: Generate Docs for Lab_3
        run: doxygen Doxygen_file/Lab_3

      # Запускаємо другий Doxyfile (вкажіть правильний шлях до нього)
      - name: Generate Docs for Project_2
        run: doxygen Doxygen_file/Project

      # Публікуємо СПІЛЬНУ папку docs, куди збереглися обидва результати
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
